# Generated by Django 6.0.6 on 2026-06-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bca_va', 'BCA Virtual Account'), ('mandiri_va', 'Mandiri Virtual Account'), ('bri_va', 'BRI Virtual Account'), ('bank_transfer', 'Bank Transfer'), ('gopay', 'GoPay'), ('ovo', 'OVO'), ('e_wallet', 'E-Wallet')], default='bank_transfer', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='travel.payment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
